In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2003.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2003,1,29,3,1651.0,1655,1912.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2003,1,30,4,1654.0,1655,1910.0,1913,UA,1017,...,2,26,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2003,1,31,5,1724.0,1655,1936.0,1913,UA,1017,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2003,1,1,3,1033.0,1035,1625.0,1634,UA,1018,...,6,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2003,1,2,4,1053.0,1035,1726.0,1634,UA,1018,...,13,46,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6488535,2003,12,5,5,1126.0,1110,1326.0,1239,DL,794,...,31,20,0,NaN,0,0.0,0.0,31.0,0.0,16.0
6488536,2003,12,5,5,2100.0,2010,2240.0,2146,DL,798,...,8,21,0,NaN,0,3.0,0.0,4.0,0.0,47.0
6488537,2003,12,5,5,1142.0,1145,1217.0,1222,DL,799,...,4,15,0,NaN,0,0.0,0.0,0.0,0.0,0.0
6488538,2003,12,5,5,623.0,620,911.0,908,DL,800,...,6,14,0,NaN,0,0.0,0.0,0.0,0.0,0.0
6488539,2003,12,5,5,1024.0,1025,1626.0,1627,DL,800,...,6,21,0,NaN,0,0.0,0.0,0.0,0.0,0.0

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 6488540 entries, 0 to 6488539
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(12), int64(12), str(5)
memory usage: 1.5 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (6488540, 29),
 188167660)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2003
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      29
DayOfWeek            int64        0     0.00        7       3
DepTime            float64   101469     1.56     1511  1651.0
CRSDepTime           int64        0     0.00     1191    1655
ArrTime            float64   112850     1.74     1618  1912.0
CRSArrTime           int64        0     0.00     1330    1913
UniqueCarrier          str        0     0.00       18      UA
FlightNum            int64        0     0.00     6921    1017
TailNum                str    26336     0.41     4996  N202UA
ActualElapsedTime  float64   112851     1.74      811   141.0
CRSElapsedTime     float64        1     0.00      538   138.0
AirTime            float64   112850     1.74     1080   119.0
ArrDelay           float64   112851     1.74     1057    -1.0
DepDelay           float64   101469     1.56     1062    -4.0
Origin                 str        0     0.00      282     ORD
Dest                   str        0     0.00      282     MSY
Distance             int64        0     0.00     1317     837
TaxiIn               int64        0     0.00     1004       5
TaxiOut              int64        0     0.00      370      17
Cancelled            int64        0     0.00        2       0
CancellationCode       str  6435446    99.18        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  2672742    41.19      735     NaN
WeatherDelay       float64  2672742    41.19      454     NaN
NASDelay           float64  2672742    41.19      508     NaN
SecurityDelay      float64  2672742    41.19      168     NaN
LateAircraftDelay  float64  2672742    41.19      447     NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum              26336     0.41
ActualElapsedTime        0     0.00
CRSElapsedTime           1     0.00
AirTime             112850     1.74
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   6435446    99.18
Diverted                 0     0.00
CarrierDelay       2672742    41.19
WeatherDelay       2672742    41.19
NASDelay           2672742    41.19
SecurityDelay      2672742    41.19
LateAircraftDelay  2672742    41.19

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2003
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      29
DayOfWeek            int64      0      0.0        7       3
DepTime            float64      0      0.0     1512  1651.0
CRSDepTime           int64      0      0.0     1191    1655
ArrTime            float64      0      0.0     1619  1912.0
CRSArrTime           int64      0      0.0     1330    1913
UniqueCarrier          str      0      0.0       18      UA
FlightNum            int64      0      0.0     6921    1017
ActualElapsedTime  float64      0      0.0      812   141.0
CRSElapsedTime     float64      1      0.0      538   138.0
ArrDelay           float64      0      0.0     1058    -1.0
DepDelay           float64      0      0.0     1063    -4.0
Origin                 str      0      0.0      282     ORD
Dest                   str      0      0.0      282     MSY
Distance             int64      0      0.0     1317     837
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(20)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2003.csv', index=False, compression='gzip')

save_to_csv(df)