In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dataverse_files/1989.csv.bz2', engine='pyarrow')
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1989,1,23,1,1419.0,1230,1742.0,1552,UA,183,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1989,1,24,2,1255.0,1230,1612.0,1552,UA,183,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1989,1,25,3,1230.0,1230,1533.0,1552,UA,183,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1989,1,26,4,1230.0,1230,1523.0,1552,UA,183,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1989,1,27,5,1232.0,1230,1513.0,1552,UA,183,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtype': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

In [5]:
adult(df)

                     dtype    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1989
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      23
DayOfWeek            int64        0     0.00        7       1
DepTime            float64    74165     1.47     1440  1419.0
CRSDepTime           int64        0     0.00     1199    1230
ArrTime            float64    89004     1.77     1440  1742.0
CRSArrTime           int64        0     0.00     1348    1552
UniqueCarrier          str        0     0.00       13      UA
FlightNum            int64        0     0.00     2699     183
TailNum            float64  5041200   100.00        0     NaN
ActualElapsedTime  float64    89004     1.77      628   323.0
CRSElapsedTime       int64        0     0.00      488     322
AirTime            float64  5041200   100.00        0     NaN
ArrDelay           float64    89004     1.77      720   110.0
DepDelay           float64    74165     1.47      788   109.0
Origin                 str        0     0.00      237     SFO
Dest                   str        0     0.00      237     HNL
Distance           float64    26988     0.54     1062  2398.0
TaxiIn             float64  5041200   100.00        0     NaN
TaxiOut            float64  5041200   100.00        0     NaN
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5041200   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5041200   100.00        0     NaN
WeatherDelay       float64  5041200   100.00        0     NaN
NASDelay           float64  5041200   100.00        0     NaN
SecurityDelay      float64  5041200   100.00        0     NaN
LateAircraftDelay  float64  5041200   100.00        0     NaN

## Missing Values

In [6]:
df.isnull().sum()

Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
DepTime                74165
CRSDepTime                 0
ArrTime                89004
CRSArrTime                 0
UniqueCarrier              0
FlightNum                  0
TailNum              5041200
ActualElapsedTime      89004
CRSElapsedTime             0
AirTime              5041200
ArrDelay               89004
DepDelay               74165
Origin                     0
Dest                       0
Distance               26988
TaxiIn               5041200
TaxiOut              5041200
Cancelled                  0
CancellationCode     5041200
Diverted                   0
CarrierDelay         5041200
WeatherDelay         5041200
NASDelay             5041200
SecurityDelay        5041200
LateAircraftDelay    5041200
dtype: int64

In [7]:
(df.isnull().mean() * 100).round(2).sort_values(ascending=False)

TailNum              100.00
SecurityDelay        100.00
TaxiIn               100.00
TaxiOut              100.00
LateAircraftDelay    100.00
CancellationCode     100.00
CarrierDelay         100.00
NASDelay             100.00
WeatherDelay         100.00
AirTime              100.00
ArrTime                1.77
ArrDelay               1.77
ActualElapsedTime      1.77
DepDelay               1.47
DepTime                1.47
Distance               0.54
CRSElapsedTime         0.00
CRSDepTime             0.00
Month                  0.00
DayofMonth             0.00
DayOfWeek              0.00
Year                   0.00
FlightNum              0.00
CRSArrTime             0.00
UniqueCarrier          0.00
Dest                   0.00
Origin                 0.00
Diverted               0.00
Cancelled              0.00
dtype: float64

In [8]:
columns = ['TailNum', 'SecurityDelay', 'TaxiIn', 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']

In [9]:
df.drop(columns=columns, inplace=True)

In [10]:
adult(df)

                     dtype  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    1989
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31      23
DayOfWeek            int64      0     0.00        7       1
DepTime            float64  74165     1.47     1440  1419.0
CRSDepTime           int64      0     0.00     1199    1230
ArrTime            float64  89004     1.77     1440  1742.0
CRSArrTime           int64      0     0.00     1348    1552
UniqueCarrier          str      0     0.00       13      UA
FlightNum            int64      0     0.00     2699     183
ActualElapsedTime  float64  89004     1.77      628   323.0
CRSElapsedTime       int64      0     0.00      488     322
ArrDelay           float64  89004     1.77      720   110.0
DepDelay           float64  74165     1.47      788   109.0
Origin                 str      0     0.00      237     SFO
Dest                   str      0     0.00      237     HNL
Distance           float64  26988     0.54     1062  2398.0
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [11]:
df['ArrTime'] = df['ArrTime'].fillna(df.ArrTime.mean())
df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df.ActualElapsedTime.mean())
df['ArrDelay'] = df['ArrDelay'].fillna(df.ArrDelay.mean())
df['DepDelay'] = df['DepDelay'].fillna(df.DepDelay.mean())
df['Distance'] = df['Distance'].fillna(0)
df['DepTime'] = df['DepTime'].fillna(df.DepTime.mean())

In [12]:
adult(df)

                     dtype  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1989
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      23
DayOfWeek            int64      0      0.0        7       1
DepTime            float64      0      0.0     1441  1419.0
CRSDepTime           int64      0      0.0     1199    1230
ArrTime            float64      0      0.0     1441  1742.0
CRSArrTime           int64      0      0.0     1348    1552
UniqueCarrier          str      0      0.0       13      UA
FlightNum            int64      0      0.0     2699     183
ActualElapsedTime  float64      0      0.0      629   323.0
CRSElapsedTime       int64      0      0.0      488     322
ArrDelay           float64      0      0.0      721   110.0
DepDelay           float64      0      0.0      789   109.0
Origin                 str      0      0.0      237     SFO
Dest                   str      0      0.0      237     HNL
Distance           float64      0      0.0     1062  2398.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [13]:
df.duplicated().sum()

np.int64(5)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.to_csv('df_1989.csv', index=False)