In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2004.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2004,1,12,1,623.0,630,901.0,915,UA,462,...,7,11,0,NaN,0,0,0,0,0,0
1,2004,1,13,2,621.0,630,911.0,915,UA,462,...,16,16,0,NaN,0,0,0,0,0,0
2,2004,1,14,3,633.0,630,920.0,915,UA,462,...,4,15,0,NaN,0,0,0,0,0,0
3,2004,1,15,4,627.0,630,859.0,915,UA,462,...,4,10,0,NaN,0,0,0,0,0,0
4,2004,1,16,5,635.0,630,918.0,915,UA,462,...,3,13,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7129265,2004,12,16,4,1645.0,1639,1715.0,1716,DL,1138,...,4,13,0,NaN,0,0,0,0,0,0
7129266,2004,12,16,4,726.0,720,1238.0,1239,DL,1139,...,10,11,0,NaN,0,0,0,0,0,0
7129267,2004,12,16,4,1336.0,1330,1507.0,1504,DL,1139,...,5,10,0,NaN,0,0,0,0,0,0
7129268,2004,12,16,4,538.0,540,720.0,723,DL,1140,...,7,12,0,NaN,0,0,0,0,0,0
7129269,2004,12,16,4,811.0,813,955.0,1008,DL,1140,...,7,12,0,NaN,0,0,0,0,0,0

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 7129270 entries, 0 to 7129269
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       int64
 25  WeatherDelay       int64
 26  NASDelay           int64
 27  SecurityDelay      int64
 28  LateAircraftDelay  int64
dtypes: float64(6), int64(18), str(5)
memory usage: 1.6 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (7129270, 29),
 206748830)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2004
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      12
DayOfWeek            int64        0     0.00        7       1
DepTime            float64   127757     1.79     1566   623.0
CRSDepTime           int64        0     0.00     1182     630
ArrTime            float64   141541     1.99     1650   901.0
CRSArrTime           int64        0     0.00     1354     915
UniqueCarrier          str        0     0.00       19      UA
FlightNum            int64        0     0.00     7726     462
TailNum                str      127     0.00     5449  N805UA
ActualElapsedTime  float64   141541     1.99      747    98.0
CRSElapsedTime       int64        0     0.00      527     105
AirTime            float64   141541     1.99     1902    80.0
ArrDelay           float64   141541     1.99     1123   -14.0
DepDelay           float64   127757     1.79     1103    -7.0
Origin                 str        0     0.00      285     ORD
Dest                   str        0     0.00      288     CLT
Distance             int64        0     0.00     1337     599
TaxiIn               int64        0     0.00     1358       7
TaxiOut              int64        0     0.00      601      11
Cancelled            int64        0     0.00        2       0
CancellationCode       str  7001506    98.21        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay         int64        0     0.00      886       0
WeatherDelay         int64        0     0.00      555       0
NASDelay             int64        0     0.00      529       0
SecurityDelay        int64        0     0.00      216       0
LateAircraftDelay    int64        0     0.00      536       0

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                127     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime           0     0.00
AirTime             141541     1.99
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   7001506    98.21
Diverted                 0     0.00
CarrierDelay             0     0.00
WeatherDelay             0     0.00
NASDelay                 0     0.00
SecurityDelay            0     0.00
LateAircraftDelay        0     0.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique sample
Year                 int64      0      0.0        1   2004
Month                int64      0      0.0       12      1
DayofMonth           int64      0      0.0       31     12
DayOfWeek            int64      0      0.0        7      1
DepTime            float64      0      0.0     1567  623.0
CRSDepTime           int64      0      0.0     1182    630
ArrTime            float64      0      0.0     1651  901.0
CRSArrTime           int64      0      0.0     1354    915
UniqueCarrier          str      0      0.0       19     UA
FlightNum            int64      0      0.0     7726    462
ActualElapsedTime  float64      0      0.0      748   98.0
CRSElapsedTime       int64      0      0.0      527    105
ArrDelay           float64      0      0.0     1124  -14.0
DepDelay           float64      0      0.0     1104   -7.0
Origin                 str      0      0.0      285    ORD
Dest                   str      0      0.0      288    CLT
Distance             int64      0      0.0     1337    599
Cancelled            int64      0      0.0        2      0
Diverted             int64      0      0.0        2      0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(11)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2004.csv', index=False, compression='gzip')

save_to_csv(df)