In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2000.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2000,1,28,5,1647.0,1647,1906.0,1859,HP,154,...,15,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2000,1,29,6,1648.0,1647,1939.0,1859,HP,154,...,5,47,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2000,1,30,7,NaN,1647,NaN,1859,HP,154,...,0,0,1,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2000,1,31,1,1645.0,1647,1852.0,1859,HP,154,...,7,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2000,1,1,6,842.0,846,1057.0,1101,HP,609,...,3,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5683042,2000,12,9,6,615.0,613,941.0,945,AA,705,...,11,18,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5683043,2000,12,10,7,619.0,613,925.0,945,AA,705,...,8,15,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5683044,2000,12,11,1,611.0,613,949.0,945,AA,705,...,8,12,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5683045,2000,12,12,2,613.0,613,1005.0,945,AA,705,...,9,18,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5683046,2000,12,13,3,614.0,613,948.0,945,AA,705,...,12,23,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5683047 entries, 0 to 5683046
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(13), int64(12), str(4)
memory usage: 1.3 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5683047, 29),
 164808363)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2000
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      28
DayOfWeek            int64        0     0.00        7       5
DepTime            float64   187490     3.30     1434  1647.0
CRSDepTime           int64        0     0.00     1183    1647
ArrTime            float64   201744     3.55     1440  1906.0
CRSArrTime           int64        0     0.00     1376    1859
UniqueCarrier          str        0     0.00       11      HP
FlightNum            int64        0     0.00     3131     154
TailNum                str        0     0.00     4036  N808AW
ActualElapsedTime  float64   201744     3.55      682   259.0
CRSElapsedTime     float64      269     0.00      499   252.0
AirTime            float64   201744     3.55      630   233.0
ArrDelay           float64   201744     3.55     1051     7.0
DepDelay           float64   187490     3.30     1031     0.0
Origin                 str        0     0.00      206     ATL
Dest                   str        0     0.00      206     PHX
Distance             int64        0     0.00     1110    1587
TaxiIn               int64        0     0.00      182      15
TaxiOut              int64        0     0.00      345      11
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5683047   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5683047   100.00        0     NaN
WeatherDelay       float64  5683047   100.00        0     NaN
NASDelay           float64  5683047   100.00        0     NaN
SecurityDelay      float64  5683047   100.00        0     NaN
LateAircraftDelay  float64  5683047   100.00        0     NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime         269     0.00
AirTime             201744     3.55
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5683047   100.00
Diverted                 0     0.00
CarrierDelay       5683047   100.00
WeatherDelay       5683047   100.00
NASDelay           5683047   100.00
SecurityDelay      5683047   100.00
LateAircraftDelay  5683047   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2000
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      28
DayOfWeek            int64      0      0.0        7       5
DepTime            float64      0      0.0     1435  1647.0
CRSDepTime           int64      0      0.0     1183    1647
ArrTime            float64      0      0.0     1441  1906.0
CRSArrTime           int64      0      0.0     1376    1859
UniqueCarrier          str      0      0.0       11      HP
FlightNum            int64      0      0.0     3131     154
ActualElapsedTime  float64      0      0.0      683   259.0
CRSElapsedTime     float64    269      0.0      499   252.0
ArrDelay           float64      0      0.0     1052     7.0
DepDelay           float64      0      0.0     1032     0.0
Origin                 str      0      0.0      206     ATL
Dest                   str      0      0.0      206     PHX
Distance             int64      0      0.0     1110    1587
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2000.csv', index=False, compression='gzip')

save_to_csv(df)