In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1993.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1993,1,29,5,1055.0,1055,1228.0,1212,US,66,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1993,1,30,6,1052.0,1055,1214.0,1212,US,66,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1993,1,31,7,1103.0,1055,1213.0,1212,US,66,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1993,1,1,5,1738.0,1730,1949.0,1941,US,68,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1993,1,3,7,1737.0,1730,1946.0,1941,US,68,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5070496,1993,12,2,4,956.0,950,1137.0,1130,CO,1671,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5070497,1993,12,3,5,950.0,950,1130.0,1130,CO,1671,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5070498,1993,12,5,7,948.0,950,1120.0,1130,CO,1671,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5070499,1993,12,6,1,950.0,950,1121.0,1130,CO,1671,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5070500,1993,12,7,2,947.0,950,1124.0,1130,CO,1671,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5070501 entries, 0 to 5070500
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            float64
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           float64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(16), int64(10), str(3)
memory usage: 1.1 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5070501, 29),
 147044529)

In [4]:
df.shape

(5070501, 29)

In [5]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1993
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      29
DayOfWeek            int64        0     0.00        7       5
DepTime            float64    59845     1.18     1425  1055.0
CRSDepTime           int64        0     0.00     1221    1055
ArrTime            float64    70178     1.38     1440  1228.0
CRSArrTime           int64        0     0.00     1347    1212
UniqueCarrier          str        0     0.00       10      US
FlightNum            int64        0     0.00     2756      66
TailNum            float64  5070501   100.00        0     NaN
ActualElapsedTime  float64    70178     1.38      610    93.0
CRSElapsedTime       int64        0     0.00      455      77
AirTime            float64  5070501   100.00        0     NaN
ArrDelay           float64    70178     1.38      668    16.0
DepDelay           float64    59845     1.18      689     0.0
Origin                 str        0     0.00      227     EWR
Dest                   str        0     0.00      227     BUF
Distance           float64     6874     0.14     1067   282.0
TaxiIn             float64  5070501   100.00        0     NaN
TaxiOut            float64  5070501   100.00        0     NaN
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5070501   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5070501   100.00        0     NaN
WeatherDelay       float64  5070501   100.00        0     NaN
NASDelay           float64  5070501   100.00        0     NaN
SecurityDelay      float64  5070501   100.00        0     NaN
LateAircraftDelay  float64  5070501   100.00        0     NaN

In [6]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0      0.0
Month                    0      0.0
DayofMonth               0      0.0
DayOfWeek                0      0.0
DepTime                  0      0.0
CRSDepTime               0      0.0
ArrTime                  0      0.0
CRSArrTime               0      0.0
UniqueCarrier            0      0.0
FlightNum                0      0.0
TailNum            5070501    100.0
ActualElapsedTime        0      0.0
CRSElapsedTime           0      0.0
AirTime            5070501    100.0
ArrDelay                 0      0.0
DepDelay                 0      0.0
Origin                   0      0.0
Dest                     0      0.0
Distance                 0      0.0
TaxiIn             5070501    100.0
TaxiOut            5070501    100.0
Cancelled                0      0.0
CancellationCode   5070501    100.0
Diverted                 0      0.0
CarrierDelay       5070501    100.0
WeatherDelay       5070501    100.0
NASDelay           5070501    100.0
SecurityDelay      5070501    100.0
LateAircraftDelay  5070501    100.0

In [7]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1993
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      29
DayOfWeek            int64      0      0.0        7       5
DepTime            float64      0      0.0     1426  1055.0
CRSDepTime           int64      0      0.0     1221    1055
ArrTime            float64      0      0.0     1441  1228.0
CRSArrTime           int64      0      0.0     1347    1212
UniqueCarrier          str      0      0.0       10      US
FlightNum            int64      0      0.0     2756      66
ActualElapsedTime  float64      0      0.0      611    93.0
CRSElapsedTime       int64      0      0.0      455      77
ArrDelay           float64      0      0.0      669    16.0
DepDelay           float64      0      0.0      690     0.0
Origin                 str      0      0.0      227     EWR
Dest                   str      0      0.0      227     BUF
Distance           float64      0      0.0     1068   282.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [8]:
def save_to_csv(df):
    df.to_csv('df_1993.csv', index=False, compression='gzip')

save_to_csv(df)