In [22]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1988.csv.bz2', engine='pyarrow')
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1988,1,9,6,1348.0,1331,1458.0,1435,PI,942,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1988,1,10,7,1334.0,1331,1443.0,1435,PI,942,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1988,1,11,1,1446.0,1331,1553.0,1435,PI,942,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1988,1,12,2,1334.0,1331,1438.0,1435,PI,942,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1988,1,13,3,1341.0,1331,1503.0,1435,PI,942,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def adult(df):
    summary = pd.DataFrame({     
        'dtype': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0],
    })
    return summary

In [4]:
adult(df)

                     dtype    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1988
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31       9
DayOfWeek            int64        0     0.00        7       6
DepTime            float64    50163     0.96     1439  1348.0
CRSDepTime           int64        0     0.00     1230    1331
ArrTime            float64    64599     1.24     1440  1458.0
CRSArrTime           int64        0     0.00     1351    1435
UniqueCarrier          str        0     0.00       14      PI
FlightNum            int64        0     0.00     2537     942
TailNum            float64  5202096   100.00        0     NaN
ActualElapsedTime  float64    64599     1.24      700    70.0
CRSElapsedTime       int64        0     0.00      502      64
AirTime            float64  5202096   100.00        0     NaN
ArrDelay           float64    64599     1.24      791    23.0
DepDelay           float64    50163     0.96      841    17.0
Origin                 str        0     0.00      238     SYR
Dest                   str        0     0.00      236     BWI
Distance           float64    11102     0.21     1094   273.0
TaxiIn             float64  5202096   100.00        0     NaN
TaxiOut            float64  5202096   100.00        0     NaN
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5202096   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5202096   100.00        0     NaN
WeatherDelay       float64  5202096   100.00        0     NaN
NASDelay           float64  5202096   100.00        0     NaN
SecurityDelay      float64  5202096   100.00        0     NaN
LateAircraftDelay  float64  5202096   100.00        0     NaN

In [5]:
df.shape

(5202096, 29)

In [6]:
df.size

150860784

In [7]:
df.columns.to_list()

['Year',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'DepTime',
 'CRSDepTime',
 'ArrTime',
 'CRSArrTime',
 'UniqueCarrier',
 'FlightNum',
 'TailNum',
 'ActualElapsedTime',
 'CRSElapsedTime',
 'AirTime',
 'ArrDelay',
 'DepDelay',
 'Origin',
 'Dest',
 'Distance',
 'TaxiIn',
 'TaxiOut',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay']

In [8]:
df.isnull().sum()

Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
DepTime                50163
CRSDepTime                 0
ArrTime                64599
CRSArrTime                 0
UniqueCarrier              0
FlightNum                  0
TailNum              5202096
ActualElapsedTime      64599
CRSElapsedTime             0
AirTime              5202096
ArrDelay               64599
DepDelay               50163
Origin                     0
Dest                       0
Distance               11102
TaxiIn               5202096
TaxiOut              5202096
Cancelled                  0
CancellationCode     5202096
Diverted                   0
CarrierDelay         5202096
WeatherDelay         5202096
NASDelay             5202096
SecurityDelay        5202096
LateAircraftDelay    5202096
dtype: int64

In [9]:
# drop columns
col = ['CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay',  'LateAircraftDelay', 'TaxiIn', 'TaxiOut', 'AirTime', 'TailNum', 'CancellationCode']
df.drop(columns=col, inplace=True)

In [10]:
(df.isnull().sum())

Year                     0
Month                    0
DayofMonth               0
DayOfWeek                0
DepTime              50163
CRSDepTime               0
ArrTime              64599
CRSArrTime               0
UniqueCarrier            0
FlightNum                0
ActualElapsedTime    64599
CRSElapsedTime           0
ArrDelay             64599
DepDelay             50163
Origin                   0
Dest                     0
Distance             11102
Cancelled                0
Diverted                 0
dtype: int64

In [11]:
(df.isnull().mean() * 100).round(2)

Year                 0.00
Month                0.00
DayofMonth           0.00
DayOfWeek            0.00
DepTime              0.96
CRSDepTime           0.00
ArrTime              1.24
CRSArrTime           0.00
UniqueCarrier        0.00
FlightNum            0.00
ActualElapsedTime    1.24
CRSElapsedTime       0.00
ArrDelay             1.24
DepDelay             0.96
Origin               0.00
Dest                 0.00
Distance             0.21
Cancelled            0.00
Diverted             0.00
dtype: float64

In [12]:
adult(df)

                     dtype  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    1988
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31       9
DayOfWeek            int64      0     0.00        7       6
DepTime            float64  50163     0.96     1439  1348.0
CRSDepTime           int64      0     0.00     1230    1331
ArrTime            float64  64599     1.24     1440  1458.0
CRSArrTime           int64      0     0.00     1351    1435
UniqueCarrier          str      0     0.00       14      PI
FlightNum            int64      0     0.00     2537     942
ActualElapsedTime  float64  64599     1.24      700    70.0
CRSElapsedTime       int64      0     0.00      502      64
ArrDelay           float64  64599     1.24      791    23.0
DepDelay           float64  50163     0.96      841    17.0
Origin                 str      0     0.00      238     SYR
Dest                   str      0     0.00      236     BWI
Distance           float64  11102     0.21     1094   273.0
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [13]:
df['Distance'] = df['Distance'].fillna(0)

In [14]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,ActualElapsedTime,CRSElapsedTime,ArrDelay,DepDelay,Origin,Dest,Distance,Cancelled,Diverted
0,1988,1,9,6,1348.0,1331,1458.0,1435,PI,942,70.0,64,23.0,17.0,SYR,BWI,273.0,0,0
1,1988,1,10,7,1334.0,1331,1443.0,1435,PI,942,69.0,64,8.0,3.0,SYR,BWI,273.0,0,0
2,1988,1,11,1,1446.0,1331,1553.0,1435,PI,942,67.0,64,78.0,75.0,SYR,BWI,273.0,0,0
3,1988,1,12,2,1334.0,1331,1438.0,1435,PI,942,64.0,64,3.0,3.0,SYR,BWI,273.0,0,0
4,1988,1,13,3,1341.0,1331,1503.0,1435,PI,942,82.0,64,28.0,10.0,SYR,BWI,273.0,0,0

In [15]:
df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean())
df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean())
df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean())
df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean())
df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean())

In [16]:
adult(df)

                     dtype  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1988
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31       9
DayOfWeek            int64      0      0.0        7       6
DepTime            float64      0      0.0     1440  1348.0
CRSDepTime           int64      0      0.0     1230    1331
ArrTime            float64      0      0.0     1441  1458.0
CRSArrTime           int64      0      0.0     1351    1435
UniqueCarrier          str      0      0.0       14      PI
FlightNum            int64      0      0.0     2537     942
ActualElapsedTime  float64      0      0.0      701    70.0
CRSElapsedTime       int64      0      0.0      502      64
ArrDelay           float64      0      0.0      792    23.0
DepDelay           float64      0      0.0      842    17.0
Origin                 str      0      0.0      238     SYR
Dest                   str      0      0.0      236     BWI
Distance           float64      0      0.0     1095   273.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [17]:
df.duplicated().sum()

np.int64(13)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
adult(df)

                     dtype  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1988
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31       9
DayOfWeek            int64      0      0.0        7       6
DepTime            float64      0      0.0     1440  1348.0
CRSDepTime           int64      0      0.0     1230    1331
ArrTime            float64      0      0.0     1441  1458.0
CRSArrTime           int64      0      0.0     1351    1435
UniqueCarrier          str      0      0.0       14      PI
FlightNum            int64      0      0.0     2537     942
ActualElapsedTime  float64      0      0.0      701    70.0
CRSElapsedTime       int64      0      0.0      502      64
ArrDelay           float64      0      0.0      792    23.0
DepDelay           float64      0      0.0      842    17.0
Origin                 str      0      0.0      238     SYR
Dest                   str      0      0.0      236     BWI
Distance           float64      0      0.0     1095   273.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [21]:
df.to_csv('df_1988.csv', index=False)