In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2006.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2006,1,11,3,743.0,745,1024.0,1018,US,343,...,45,13,0,NaN,0,0,0,0,0,0
1,2006,1,11,3,1053.0,1053,1313.0,1318,US,613,...,27,19,0,NaN,0,0,0,0,0,0
2,2006,1,11,3,1915.0,1915,2110.0,2133,US,617,...,4,11,0,NaN,0,0,0,0,0,0
3,2006,1,11,3,1753.0,1755,1925.0,1933,US,300,...,16,10,0,NaN,0,0,0,0,0,0
4,2006,1,11,3,824.0,832,1015.0,1015,US,765,...,27,12,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7141917,2006,12,29,5,1246.0,1249,1452.0,1459,DL,1675,...,6,12,0,NaN,0,0,0,0,0,0
7141918,2006,12,29,5,1225.0,1155,2033.0,1931,DL,1676,...,12,35,0,NaN,0,30,0,32,0,0
7141919,2006,12,29,5,2118.0,2115,2254.0,2241,DL,1676,...,9,27,0,NaN,0,0,0,0,0,0
7141920,2006,12,29,5,2122.0,2127,2209.0,2223,DL,1677,...,5,21,0,NaN,0,0,0,0,0,0
7141921,2006,12,29,5,2042.0,2045,2213.0,2235,DL,1678,...,5,15,0,NaN,0,0,0,0,0,0

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 7141922 entries, 0 to 7141921
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       int64
 25  WeatherDelay       int64
 26  NASDelay           int64
 27  SecurityDelay      int64
 28  LateAircraftDelay  int64
dtypes: float64(7), int64(17), str(5)
memory usage: 1.6 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (7141922, 29),
 207115738)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2006
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      11
DayOfWeek            int64        0     0.00        7       3
DepTime            float64   121934     1.71     1552   743.0
CRSDepTime           int64        0     0.00     1179     745
ArrTime            float64   138120     1.93     1635  1024.0
CRSArrTime           int64        0     0.00     1384    1018
UniqueCarrier          str        0     0.00       20      US
FlightNum            int64        0     0.00     7465     343
TailNum                str        0     0.00     5081  N657AW
ActualElapsedTime  float64   138120     1.93      750   281.0
CRSElapsedTime     float64        4     0.00      556   273.0
AirTime            float64   138120     1.93      872   223.0
ArrDelay           float64   138120     1.93     1136     6.0
DepDelay           float64   121934     1.71     1178    -2.0
Origin                 str        0     0.00      289     ATL
Dest                   str        0     0.00      296     PHX
Distance             int64        0     0.00     1395    1587
TaxiIn               int64        0     0.00      268      45
TaxiOut              int64        0     0.00      326      13
Cancelled            int64        0     0.00        2       0
CancellationCode       str  7019988    98.29        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay         int64        0     0.00      949       0
WeatherDelay         int64        0     0.00      537       0
NASDelay             int64        0     0.00      547       0
SecurityDelay        int64        0     0.00      205       0
LateAircraftDelay    int64        0     0.00      575       0

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime           4     0.00
AirTime             138120     1.93
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   7019988    98.29
Diverted                 0     0.00
CarrierDelay             0     0.00
WeatherDelay             0     0.00
NASDelay                 0     0.00
SecurityDelay            0     0.00
LateAircraftDelay        0     0.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2006
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      11
DayOfWeek            int64      0      0.0        7       3
DepTime            float64      0      0.0     1553   743.0
CRSDepTime           int64      0      0.0     1179     745
ArrTime            float64      0      0.0     1636  1024.0
CRSArrTime           int64      0      0.0     1384    1018
UniqueCarrier          str      0      0.0       20      US
FlightNum            int64      0      0.0     7465     343
ActualElapsedTime  float64      0      0.0      751   281.0
CRSElapsedTime     float64      4      0.0      556   273.0
ArrDelay           float64      0      0.0     1137     6.0
DepDelay           float64      0      0.0     1179    -2.0
Origin                 str      0      0.0      289     ATL
Dest                   str      0      0.0      296     PHX
Distance             int64      0      0.0     1395    1587
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(8)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2006.csv', index=False, compression='gzip')

save_to_csv(df)