In [ ]:
import pandas as pd

In [3]:
df = pd.read_csv('dataverse_files/1987.csv.bz2', engine='pyarrow')
df.head(5)

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1987,10,14,3,741.0,730,912.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1987,10,15,4,729.0,730,903.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1987,10,17,6,741.0,730,918.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1987,10,18,7,729.0,730,847.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1987,10,19,1,749.0,730,922.0,849,PS,1451,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtype': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

In [5]:
adult(df)

                     dtype    nulls  nulls_%  nunique sample
Year                 int64        0     0.00        1   1987
Month                int64        0     0.00        3     10
DayofMonth           int64        0     0.00       31     14
DayOfWeek            int64        0     0.00        7      3
DepTime            float64    19685     1.50     1430  741.0
CRSDepTime           int64        0     0.00     1174    730
ArrTime            float64    23500     1.79     1440  912.0
CRSArrTime           int64        0     0.00     1301    849
UniqueCarrier          str        0     0.00       14     PS
FlightNum            int64        0     0.00     2161   1451
TailNum            float64  1311826   100.00        0    NaN
ActualElapsedTime  float64    23500     1.79      647   91.0
CRSElapsedTime       int64        0     0.00      431     79
AirTime            float64  1311826   100.00        0    NaN
ArrDelay           float64    23500     1.79      672   23.0
DepDelay           float64    19685     1.50      605   11.0
Origin                 str        0     0.00      237    SAN
Dest                   str        0     0.00      237    SFO
Distance           float64     1015     0.08     1026  447.0
TaxiIn             float64  1311826   100.00        0    NaN
TaxiOut            float64  1311826   100.00        0    NaN
Cancelled            int64        0     0.00        2      0
CancellationCode   float64  1311826   100.00        0    NaN
Diverted             int64        0     0.00        2      0
CarrierDelay       float64  1311826   100.00        0    NaN
WeatherDelay       float64  1311826   100.00        0    NaN
NASDelay           float64  1311826   100.00        0    NaN
SecurityDelay      float64  1311826   100.00        0    NaN
LateAircraftDelay  float64  1311826   100.00        0    NaN

## Missing Values

In [6]:
df.isnull().sum()

Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
DepTime                19685
CRSDepTime                 0
ArrTime                23500
CRSArrTime                 0
UniqueCarrier              0
FlightNum                  0
TailNum              1311826
ActualElapsedTime      23500
CRSElapsedTime             0
AirTime              1311826
ArrDelay               23500
DepDelay               19685
Origin                     0
Dest                       0
Distance                1015
TaxiIn               1311826
TaxiOut              1311826
Cancelled                  0
CancellationCode     1311826
Diverted                   0
CarrierDelay         1311826
WeatherDelay         1311826
NASDelay             1311826
SecurityDelay        1311826
LateAircraftDelay    1311826
dtype: int64

In [7]:
(df.isnull().mean() * 100).round(2).sort_values(ascending=False)

TailNum              100.00
SecurityDelay        100.00
TaxiIn               100.00
TaxiOut              100.00
LateAircraftDelay    100.00
CancellationCode     100.00
CarrierDelay         100.00
NASDelay             100.00
WeatherDelay         100.00
AirTime              100.00
ArrTime                1.79
ArrDelay               1.79
ActualElapsedTime      1.79
DepDelay               1.50
DepTime                1.50
Distance               0.08
CRSElapsedTime         0.00
CRSDepTime             0.00
Month                  0.00
DayofMonth             0.00
DayOfWeek              0.00
Year                   0.00
FlightNum              0.00
CRSArrTime             0.00
UniqueCarrier          0.00
Dest                   0.00
Origin                 0.00
Diverted               0.00
Cancelled              0.00
dtype: float64

In [8]:
df[df['DepTime'].isnull()]

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
52,1987,10,12,1,NaN,1505,NaN,1608,PS,1453,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
79,1987,10,12,1,NaN,1635,NaN,1732,PS,1454,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
98,1987,10,6,2,NaN,830,NaN,937,PS,1457,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
161,1987,10,29,4,NaN,930,NaN,1040,PS,1459,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
263,1987,10,22,4,NaN,2000,NaN,2059,PS,1465,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1311677,1987,12,2,3,NaN,1430,NaN,1545,CO,633,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
1311687,1987,12,15,2,NaN,1455,NaN,1614,CO,633,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
1311698,1987,12,28,1,NaN,1455,NaN,1614,CO,633,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
1311783,1987,12,28,1,NaN,1510,NaN,1810,CO,636,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN
1311800,1987,12,15,2,NaN,1615,NaN,1733,CO,637,...,NaN,NaN,1,NaN,0,NaN,NaN,NaN,NaN,NaN

In [11]:
adult(df)

                     dtype    nulls  nulls_%  nunique sample
Year                 int64        0     0.00        1   1987
Month                int64        0     0.00        3     10
DayofMonth           int64        0     0.00       31     14
DayOfWeek            int64        0     0.00        7      3
DepTime            float64    19685     1.50     1430  741.0
CRSDepTime           int64        0     0.00     1174    730
ArrTime            float64    23500     1.79     1440  912.0
CRSArrTime           int64        0     0.00     1301    849
UniqueCarrier          str        0     0.00       14     PS
FlightNum            int64        0     0.00     2161   1451
TailNum            float64  1311826   100.00        0    NaN
ActualElapsedTime  float64    23500     1.79      647   91.0
CRSElapsedTime       int64        0     0.00      431     79
AirTime            float64  1311826   100.00        0    NaN
ArrDelay           float64    23500     1.79      672   23.0
DepDelay           float64    19685     1.50      605   11.0
Origin                 str        0     0.00      237    SAN
Dest                   str        0     0.00      237    SFO
Distance           float64     1015     0.08     1026  447.0
TaxiIn             float64  1311826   100.00        0    NaN
TaxiOut            float64  1311826   100.00        0    NaN
Cancelled            int64        0     0.00        2      0
CancellationCode   float64  1311826   100.00        0    NaN
Diverted             int64        0     0.00        2      0
CarrierDelay       float64  1311826   100.00        0    NaN
WeatherDelay       float64  1311826   100.00        0    NaN
NASDelay           float64  1311826   100.00        0    NaN
SecurityDelay      float64  1311826   100.00        0    NaN
LateAircraftDelay  float64  1311826   100.00        0    NaN

In [12]:
col = ['TailNum', 'AirTime', 'TaxiIn', 'TaxiOut', 'CancellationCode', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']

In [13]:
df.drop(columns=col, inplace=True)

In [14]:
adult(df)

                     dtype  nulls  nulls_%  nunique sample
Year                 int64      0     0.00        1   1987
Month                int64      0     0.00        3     10
DayofMonth           int64      0     0.00       31     14
DayOfWeek            int64      0     0.00        7      3
DepTime            float64  19685     1.50     1430  741.0
CRSDepTime           int64      0     0.00     1174    730
ArrTime            float64  23500     1.79     1440  912.0
CRSArrTime           int64      0     0.00     1301    849
UniqueCarrier          str      0     0.00       14     PS
FlightNum            int64      0     0.00     2161   1451
ActualElapsedTime  float64  23500     1.79      647   91.0
CRSElapsedTime       int64      0     0.00      431     79
ArrDelay           float64  23500     1.79      672   23.0
DepDelay           float64  19685     1.50      605   11.0
Origin                 str      0     0.00      237    SAN
Dest                   str      0     0.00      237    SFO
Distance           float64   1015     0.08     1026  447.0
Cancelled            int64      0     0.00        2      0
Diverted             int64      0     0.00        2      0

In [15]:
df['DepTime'] = df['DepTime'].fillna(df.DepTime.mean())

In [16]:
df['ArrTime'] = df['ArrTime'].fillna(df.ArrTime.mean())
df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df.ActualElapsedTime.mean())
df['ArrDelay'] = df['ArrDelay'].fillna(df.ArrDelay.mean())
df['DepDelay'] = df['DepDelay'].fillna(df.DepDelay.mean())
df['Distance'] = df['Distance'].fillna(0)

In [17]:
adult(df)

                     dtype  nulls  nulls_%  nunique sample
Year                 int64      0      0.0        1   1987
Month                int64      0      0.0        3     10
DayofMonth           int64      0      0.0       31     14
DayOfWeek            int64      0      0.0        7      3
DepTime            float64      0      0.0     1431  741.0
CRSDepTime           int64      0      0.0     1174    730
ArrTime            float64      0      0.0     1441  912.0
CRSArrTime           int64      0      0.0     1301    849
UniqueCarrier          str      0      0.0       14     PS
FlightNum            int64      0      0.0     2161   1451
ActualElapsedTime  float64      0      0.0      648   91.0
CRSElapsedTime       int64      0      0.0      431     79
ArrDelay           float64      0      0.0      673   23.0
DepDelay           float64      0      0.0      606   11.0
Origin                 str      0      0.0      237    SAN
Dest                   str      0      0.0      237    SFO
Distance           float64      0      0.0     1026  447.0
Cancelled            int64      0      0.0        2      0
Diverted             int64      0      0.0        2      0

In [18]:
df.duplicated().sum()

np.int64(72)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.to_csv('df_1987.csv', index=False)