In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2002.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2002,1,13,7,2231.0,2235,2342.0,2353,US,723,...,3,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2002,1,14,1,2230.0,2235,2347.0,2353,US,723,...,3,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2002,1,15,2,2230.0,2235,2342.0,2353,US,723,...,3,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2002,1,16,3,2230.0,2235,2340.0,2353,US,723,...,3,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2002,1,17,4,2227.0,2235,2345.0,2353,US,723,...,5,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5271354,2002,12,9,1,2107.0,2115,503.0,457,CO,1686,...,5,7,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5271355,2002,12,10,2,2104.0,2115,505.0,457,CO,1686,...,4,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5271356,2002,12,11,3,2128.0,2115,543.0,457,CO,1686,...,11,22,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5271357,2002,12,12,4,2109.0,2115,508.0,502,CO,1686,...,5,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5271358,2002,12,13,5,2105.0,2115,515.0,502,CO,1686,...,8,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5271359 entries, 0 to 5271358
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            object
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(12), int64(13), object(1), str(3)
memory usage: 1.2+ GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5271359, 29),
 152869411)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique           sample
Year                 int64        0     0.00        1             2002
Month                int64        0     0.00       12                1
DayofMonth           int64        0     0.00       31               13
DayOfWeek            int64        0     0.00        7                7
DepTime            float64    65143     1.24     1393           2231.0
CRSDepTime           int64        0     0.00     1160             2235
ArrTime            float64    73499     1.39     1440           2342.0
CRSArrTime           int64        0     0.00     1319             2353
UniqueCarrier          str        0     0.00       10               US
FlightNum            int64        0     0.00     4929              723
TailNum             object    29924     0.57     7768  b'N709\xe4\xe6'
ActualElapsedTime  float64    73499     1.39      689             71.0
CRSElapsedTime       int64        0     0.00      496               78
AirTime            float64    73620     1.40      682             55.0
ArrDelay           float64    73499     1.39     1054            -11.0
DepDelay           float64    65143     1.24     1053             -4.0
Origin                 str        0     0.00      218              PIT
Dest                   str        0     0.00      219              CLT
Distance             int64        0     0.00     1084              366
TaxiIn               int64        0     0.00      898                3
TaxiOut              int64        0     0.00      350               13
Cancelled            int64        0     0.00        2                0
CancellationCode   float64  5271359   100.00        0              NaN
Diverted             int64        0     0.00        2                0
CarrierDelay       float64  5271359   100.00        0              NaN
WeatherDelay       float64  5271359   100.00        0              NaN
NASDelay           float64  5271359   100.00        0              NaN
SecurityDelay      float64  5271359   100.00        0              NaN
LateAircraftDelay  float64  5271359   100.00        0              NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum              29924     0.57
ActualElapsedTime        0     0.00
CRSElapsedTime           0     0.00
AirTime              73620     1.40
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5271359   100.00
Diverted                 0     0.00
CarrierDelay       5271359   100.00
WeatherDelay       5271359   100.00
NASDelay           5271359   100.00
SecurityDelay      5271359   100.00
LateAircraftDelay  5271359   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2002
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      13
DayOfWeek            int64      0      0.0        7       7
DepTime            float64      0      0.0     1394  2231.0
CRSDepTime           int64      0      0.0     1160    2235
ArrTime            float64      0      0.0     1441  2342.0
CRSArrTime           int64      0      0.0     1319    2353
UniqueCarrier          str      0      0.0       10      US
FlightNum            int64      0      0.0     4929     723
ActualElapsedTime  float64      0      0.0      690    71.0
CRSElapsedTime       int64      0      0.0      496      78
ArrDelay           float64      0      0.0     1055   -11.0
DepDelay           float64      0      0.0     1054    -4.0
Origin                 str      0      0.0      218     PIT
Dest                   str      0      0.0      219     CLT
Distance             int64      0      0.0     1084     366
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2002.csv', index=False, compression='gzip')

save_to_csv(df)