In [9]:
import pandas as pd

In [10]:
df = pd.read_csv('dataverse_files/2001.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2001,1,17,3,1806.0,1810,1931.0,1934,US,375,...,5,20,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,2001,1,18,4,1805.0,1810,1938.0,1934,US,375,...,9,20,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2001,1,19,5,1821.0,1810,1957.0,1934,US,375,...,6,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2001,1,20,6,1807.0,1810,1944.0,1934,US,375,...,4,27,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2001,1,21,7,1810.0,1810,1954.0,1934,US,375,...,4,38,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967775,2001,12,14,5,704.0,700,1159.0,1155,DL,678,...,14,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5967776,2001,12,15,6,708.0,700,1158.0,1155,DL,678,...,9,18,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5967777,2001,12,16,7,656.0,700,1147.0,1155,DL,678,...,7,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5967778,2001,12,17,1,656.0,700,1151.0,1155,DL,678,...,13,11,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5967779,2001,12,18,2,709.0,700,1158.0,1155,DL,678,...,10,16,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [11]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5967780 entries, 0 to 5967779
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            object
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(12), int64(13), object(1), str(3)
memory usage: 1.3+ GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5967780, 29),
 173065620)

In [12]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique           sample
Year                 int64        0     0.00        1             2001
Month                int64        0     0.00       12                1
DayofMonth           int64        0     0.00       31               17
DayOfWeek            int64        0     0.00        7                3
DepTime            float64   231198     3.87     1420           1806.0
CRSDepTime           int64        0     0.00     1179             1810
ArrTime            float64   244107     4.09     1440           1931.0
CRSArrTime           int64        0     0.00     1357             1934
UniqueCarrier          str        0     0.00       12               US
FlightNum            int64        0     0.00     5295              375
TailNum             object        0     0.00     4561  b'N700\xe4\xe6'
ActualElapsedTime  float64   244107     4.09      679             85.0
CRSElapsedTime       int64        0     0.00      499               84
AirTime            float64   244107     4.09      647             60.0
ArrDelay           float64   244107     4.09     1001             -3.0
DepDelay           float64   231198     3.87      977             -4.0
Origin                 str        0     0.00      231              BWI
Dest                   str        0     0.00      230              CLT
Distance             int64        0     0.00     1150              361
TaxiIn               int64        0     0.00      207                5
TaxiOut              int64        0     0.00      308               20
Cancelled            int64        0     0.00        2                0
CancellationCode   float64  5967780   100.00        0              NaN
Diverted             int64        0     0.00        2                0
CarrierDelay       float64  5967780   100.00        0              NaN
WeatherDelay       float64  5967780   100.00        0              NaN
NASDelay           float64  5967780   100.00        0              NaN
SecurityDelay      float64  5967780   100.00        0              NaN
LateAircraftDelay  float64  5967780   100.00        0              NaN

In [13]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime           0     0.00
AirTime             244107     4.09
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5967780   100.00
Diverted                 0     0.00
CarrierDelay       5967780   100.00
WeatherDelay       5967780   100.00
NASDelay           5967780   100.00
SecurityDelay      5967780   100.00
LateAircraftDelay  5967780   100.00

In [14]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2001
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      17
DayOfWeek            int64      0      0.0        7       3
DepTime            float64      0      0.0     1421  1806.0
CRSDepTime           int64      0      0.0     1179    1810
ArrTime            float64      0      0.0     1441  1931.0
CRSArrTime           int64      0      0.0     1357    1934
UniqueCarrier          str      0      0.0       12      US
FlightNum            int64      0      0.0     5295     375
ActualElapsedTime  float64      0      0.0      680    85.0
CRSElapsedTime       int64      0      0.0      499      84
ArrDelay           float64      0      0.0     1002    -3.0
DepDelay           float64      0      0.0      978    -4.0
Origin                 str      0      0.0      231     BWI
Dest                   str      0      0.0      230     CLT
Distance             int64      0      0.0     1150     361
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [15]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [16]:
def save_to_csv(df):
    df.to_csv('df_2001.csv', index=False, compression='gzip')

save_to_csv(df)