In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2007.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2007,1,1,1,1232.0,1225,1341.0,1340,WN,2891,...,4,11,0,NaN,0,0,0,0,0,0
1,2007,1,1,1,1918.0,1905,2043.0,2035,WN,462,...,5,6,0,NaN,0,0,0,0,0,0
2,2007,1,1,1,2206.0,2130,2334.0,2300,WN,1229,...,6,9,0,NaN,0,3,0,0,0,31
3,2007,1,1,1,1230.0,1200,1356.0,1330,WN,1355,...,3,8,0,NaN,0,23,0,0,0,3
4,2007,1,1,1,831.0,830,957.0,1000,WN,2278,...,3,9,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7453210,2007,12,15,6,1558.0,1605,1749.0,1736,DL,58,...,14,17,0,NaN,0,0,0,0,0,0
7453211,2007,12,15,6,1902.0,1851,2110.0,2105,DL,59,...,6,21,0,NaN,0,0,0,0,0,0
7453212,2007,12,15,6,1024.0,1025,1750.0,1735,DL,61,...,14,19,0,NaN,0,0,0,15,0,0
7453213,2007,12,15,6,1353.0,1315,1658.0,1622,DL,62,...,11,14,0,NaN,0,0,0,0,0,36
7453214,2007,12,15,6,1824.0,1800,2001.0,1928,DL,63,...,10,26,0,NaN,0,24,0,9,0,0

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 7453215 entries, 0 to 7453214
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       int64
 25  WeatherDelay       int64
 26  NASDelay           int64
 27  SecurityDelay      int64
 28  LateAircraftDelay  int64
dtypes: float64(7), int64(17), str(5)
memory usage: 1.7 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (7453215, 29),
 216143235)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2007
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31       1
DayOfWeek            int64        0     0.00        7       1
DepTime            float64   160748     2.16     1439  1232.0
CRSDepTime           int64        0     0.00     1188    1225
ArrTime            float64   177927     2.39     1440  1341.0
CRSArrTime           int64        0     0.00     1398    1340
UniqueCarrier          str        0     0.00       20      WN
FlightNum            int64        0     0.00     7596    2891
TailNum                str       22     0.00     5505    N351
ActualElapsedTime  float64   177927     2.39      692    69.0
CRSElapsedTime     float64      994     0.01      561    75.0
AirTime            float64   177927     2.39      667    54.0
ArrDelay           float64   177927     2.39     1232     1.0
DepDelay           float64   160748     2.16     1226     7.0
Origin                 str        0     0.00      304     SMF
Dest                   str        0     0.00      310     ONT
Distance             int64        0     0.00     1438     389
TaxiIn               int64        0     0.00      202       4
TaxiOut              int64        0     0.00      334      11
Cancelled            int64        0     0.00        2       0
CancellationCode       str  7292466    97.84        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay         int64        0     0.00     1045       0
WeatherDelay         int64        0     0.00      623       0
NASDelay             int64        0     0.00      570       0
SecurityDelay        int64        0     0.00      179       0
LateAircraftDelay    int64        0     0.00      585       0

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                 22     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime         994     0.01
AirTime             177927     2.39
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   7292466    97.84
Diverted                 0     0.00
CarrierDelay             0     0.00
WeatherDelay             0     0.00
NASDelay                 0     0.00
SecurityDelay            0     0.00
LateAircraftDelay        0     0.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    2007
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31       1
DayOfWeek            int64      0     0.00        7       1
DepTime            float64      0     0.00     1440  1232.0
CRSDepTime           int64      0     0.00     1188    1225
ArrTime            float64      0     0.00     1441  1341.0
CRSArrTime           int64      0     0.00     1398    1340
UniqueCarrier          str      0     0.00       20      WN
FlightNum            int64      0     0.00     7596    2891
ActualElapsedTime  float64      0     0.00      693    69.0
CRSElapsedTime     float64    994     0.01      561    75.0
ArrDelay           float64      0     0.00     1233     1.0
DepDelay           float64      0     0.00     1227     7.0
Origin                 str      0     0.00      304     SMF
Dest                   str      0     0.00      310     ONT
Distance             int64      0     0.00     1438     389
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(29)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2007.csv', index=False, compression='gzip')

save_to_csv(df)