In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1998.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1998,1,17,6,715.0,715,840.0,840,WN,76,...,3,5,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1998,1,18,7,715.0,715,830.0,840,WN,76,...,2,6,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1998,1,19,1,715.0,715,831.0,840,WN,76,...,3,5,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1998,1,20,2,715.0,715,836.0,840,WN,76,...,3,12,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1998,1,21,3,715.0,715,836.0,840,WN,76,...,3,6,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5384716,1998,12,27,7,1141.0,1145,1453.0,1457,UA,450,...,10,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5384717,1998,12,28,1,1153.0,1145,1520.0,1457,UA,450,...,25,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5384718,1998,12,29,2,1154.0,1145,1507.0,1457,UA,450,...,7,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5384719,1998,12,30,3,1209.0,1145,1510.0,1457,UA,450,...,3,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5384720,1998,12,31,4,1144.0,1145,1513.0,1457,UA,450,...,33,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5384721 entries, 0 to 5384720
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(13), int64(12), str(4)
memory usage: 1.2 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5384721, 29),
 156156909)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique sample
Year                 int64        0     0.00        1   1998
Month                int64        0     0.00       12      1
DayofMonth           int64        0     0.00       31     17
DayOfWeek            int64        0     0.00        7      6
DepTime            float64   144509     2.68     1433  715.0
CRSDepTime           int64        0     0.00     1177    715
ArrTime            float64   157670     2.93     1440  840.0
CRSArrTime           int64        0     0.00     1381    840
UniqueCarrier          str        0     0.00       10     WN
FlightNum            int64        0     0.00     2940     76
TailNum                str        0     0.00     3724   N520
ActualElapsedTime  float64   157670     2.93      664  145.0
CRSElapsedTime     float64     2386     0.04      481  145.0
AirTime            float64   157670     2.93      616  137.0
ArrDelay           float64   157670     2.93      936    0.0
DepDelay           float64   144509     2.68      950    0.0
Origin                 str        0     0.00      207    AUS
Dest                   str        0     0.00      208    PHX
Distance             int64        0     0.00     1051    872
TaxiIn               int64        0     0.00      204      3
TaxiOut              int64        0     0.00      306      5
Cancelled            int64        0     0.00        2      0
CancellationCode   float64  5384721   100.00        0    NaN
Diverted             int64        0     0.00        2      0
CarrierDelay       float64  5384721   100.00        0    NaN
WeatherDelay       float64  5384721   100.00        0    NaN
NASDelay           float64  5384721   100.00        0    NaN
SecurityDelay      float64  5384721   100.00        0    NaN
LateAircraftDelay  float64  5384721   100.00        0    NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime        2386     0.04
AirTime             157670     2.93
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5384721   100.00
Diverted                 0     0.00
CarrierDelay       5384721   100.00
WeatherDelay       5384721   100.00
NASDelay           5384721   100.00
SecurityDelay      5384721   100.00
LateAircraftDelay  5384721   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique sample
Year                 int64      0     0.00        1   1998
Month                int64      0     0.00       12      1
DayofMonth           int64      0     0.00       31     17
DayOfWeek            int64      0     0.00        7      6
DepTime            float64      0     0.00     1434  715.0
CRSDepTime           int64      0     0.00     1177    715
ArrTime            float64      0     0.00     1441  840.0
CRSArrTime           int64      0     0.00     1381    840
UniqueCarrier          str      0     0.00       10     WN
FlightNum            int64      0     0.00     2940     76
ActualElapsedTime  float64      0     0.00      665  145.0
CRSElapsedTime     float64   2386     0.04      481  145.0
ArrDelay           float64      0     0.00      937    0.0
DepDelay           float64      0     0.00      951    0.0
Origin                 str      0     0.00      207    AUS
Dest                   str      0     0.00      208    PHX
Distance             int64      0     0.00     1051    872
Cancelled            int64      0     0.00        2      0
Diverted             int64      0     0.00        2      0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_1998.csv', index=False, compression='gzip')

save_to_csv(df)