In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('dataverse_files/1990.csv.bz2', engine='python')

In [23]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,ActualElapsedTime,CRSElapsedTime,ArrDelay,DepDelay,Origin,Dest,Distance,Cancelled,Diverted
0,1990,1,3,3,1707.0,1630,1755.0,1723,US,29,48.0,53,32.0,37.0,CMH,IND,182.0,0,0
1,1990,1,4,4,1706.0,1630,1807.0,1723,US,29,61.0,53,44.0,36.0,CMH,IND,182.0,0,0
2,1990,1,5,5,1629.0,1630,1715.0,1723,US,29,46.0,53,-8.0,-1.0,CMH,IND,182.0,0,0
3,1990,1,6,6,1633.0,1630,1718.0,1723,US,29,45.0,53,-5.0,3.0,CMH,IND,182.0,0,0
4,1990,1,8,1,1630.0,1630,1726.0,1723,US,29,56.0,53,3.0,0.0,CMH,IND,182.0,0,0

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

In [5]:
adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1990
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31       3
DayOfWeek            int64        0     0.00        7       3
DepTime            float64    52458     1.00     1440  1707.0
CRSDepTime           int64        0     0.00     1226    1630
ArrTime            float64    68412     1.30     1440  1755.0
CRSArrTime           int64        0     0.00     1362    1723
UniqueCarrier          str        0     0.00       12      US
FlightNum            int64        0     0.00     2765      29
TailNum            float64  5270893   100.00        0     NaN
ActualElapsedTime  float64    68412     1.30      631    48.0
CRSElapsedTime       int64        0     0.00      481      53
AirTime            float64  5270893   100.00        0     NaN
ArrDelay           float64    68412     1.30      738    32.0
DepDelay           float64    52458     1.00      749    37.0
Origin                 str        0     0.00      235     CMH
Dest                   str        0     0.00      236     IND
Distance           float64    93437     1.77     1085   182.0
TaxiIn             float64  5270893   100.00        0     NaN
TaxiOut            float64  5270893   100.00        0     NaN
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5270893   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5270893   100.00        0     NaN
WeatherDelay       float64  5270893   100.00        0     NaN
NASDelay           float64  5270893   100.00        0     NaN
SecurityDelay      float64  5270893   100.00        0     NaN
LateAircraftDelay  float64  5270893   100.00        0     NaN

In [6]:
df.isnull().sum()

Year                       0
Month                      0
DayofMonth                 0
DayOfWeek                  0
DepTime                52458
CRSDepTime                 0
ArrTime                68412
CRSArrTime                 0
UniqueCarrier              0
FlightNum                  0
TailNum              5270893
ActualElapsedTime      68412
CRSElapsedTime             0
AirTime              5270893
ArrDelay               68412
DepDelay               52458
Origin                     0
Dest                       0
Distance               93437
TaxiIn               5270893
TaxiOut              5270893
Cancelled                  0
CancellationCode     5270893
Diverted                   0
CarrierDelay         5270893
WeatherDelay         5270893
NASDelay             5270893
SecurityDelay        5270893
LateAircraftDelay    5270893
dtype: int64

In [7]:
(df.isnull().mean() * 100).round(2).sort_values(ascending=False)

TailNum              100.00
SecurityDelay        100.00
TaxiIn               100.00
TaxiOut              100.00
LateAircraftDelay    100.00
CancellationCode     100.00
CarrierDelay         100.00
NASDelay             100.00
WeatherDelay         100.00
AirTime              100.00
Distance               1.77
ArrTime                1.30
ActualElapsedTime      1.30
ArrDelay               1.30
DepTime                1.00
DepDelay               1.00
CRSElapsedTime         0.00
CRSDepTime             0.00
Month                  0.00
DayofMonth             0.00
DayOfWeek              0.00
Year                   0.00
FlightNum              0.00
CRSArrTime             0.00
UniqueCarrier          0.00
Dest                   0.00
Origin                 0.00
Diverted               0.00
Cancelled              0.00
dtype: float64

In [8]:
columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
df.drop(columns=columns, inplace=True)

In [10]:
adult(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    1990
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31       3
DayOfWeek            int64      0     0.00        7       3
DepTime            float64  52458     1.00     1440  1707.0
CRSDepTime           int64      0     0.00     1226    1630
ArrTime            float64  68412     1.30     1440  1755.0
CRSArrTime           int64      0     0.00     1362    1723
UniqueCarrier          str      0     0.00       12      US
FlightNum            int64      0     0.00     2765      29
ActualElapsedTime  float64  68412     1.30      631    48.0
CRSElapsedTime       int64      0     0.00      481      53
ArrDelay           float64  68412     1.30      738    32.0
DepDelay           float64  52458     1.00      749    37.0
Origin                 str      0     0.00      235     CMH
Dest                   str      0     0.00      236     IND
Distance           float64  93437     1.77     1085   182.0
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [24]:
df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
df['Distance'] = df['Distance'].fillna(0)

In [25]:
adult(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1990
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31       3
DayOfWeek            int64      0      0.0        7       3
DepTime            float64      0      0.0     1441  1707.0
CRSDepTime           int64      0      0.0     1226    1630
ArrTime            float64      0      0.0     1441  1755.0
CRSArrTime           int64      0      0.0     1362    1723
UniqueCarrier          str      0      0.0       12      US
FlightNum            int64      0      0.0     2765      29
ActualElapsedTime  float64      0      0.0      632    48.0
CRSElapsedTime       int64      0      0.0      481      53
ArrDelay           float64      0      0.0      739    32.0
DepDelay           float64      0      0.0      750    37.0
Origin                 str      0      0.0      235     CMH
Dest                   str      0      0.0      236     IND
Distance           float64      0      0.0     1086   182.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.to_csv('df_1990.csv', index=False)