In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1992.csv.bz2', engine='pyarrow')

In [3]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1992,1,2,4,748.0,750,851.0,846,US,53,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1992,1,3,5,750.0,750,843.0,846,US,53,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1992,1,4,6,747.0,750,843.0,846,US,53,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1992,1,5,7,750.0,750,850.0,846,US,53,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1992,1,6,1,752.0,750,838.0,846,US,53,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [4]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5092157 entries, 0 to 5092156
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            float64
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           float64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(16), int64(10), str(3)
memory usage: 1.1 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5092157, 29),
 147672553)

In [5]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

In [6]:
adult(df)

                    dtypes    nulls  nulls_%  nunique sample
Year                 int64        0     0.00        1   1992
Month                int64        0     0.00       12      1
DayofMonth           int64        0     0.00       31      2
DayOfWeek            int64        0     0.00        7      4
DepTime            float64    52836     1.04     1433  748.0
CRSDepTime           int64        0     0.00     1260    750
ArrTime            float64    64220     1.26     1440  851.0
CRSArrTime           int64        0     0.00     1363    846
UniqueCarrier          str        0     0.00       10     US
FlightNum            int64        0     0.00     2626     53
TailNum            float64  5092157   100.00        0    NaN
ActualElapsedTime  float64    64220     1.26      617   63.0
CRSElapsedTime       int64        0     0.00      462     56
AirTime            float64  5092157   100.00        0    NaN
ArrDelay           float64    64220     1.26      696    5.0
DepDelay           float64    52836     1.04      700   -2.0
Origin                 str        0     0.00      233    CMH
Dest                   str        0     0.00      233    IND
Distance           float64     7387     0.15     1084  182.0
TaxiIn             float64  5092157   100.00        0    NaN
TaxiOut            float64  5092157   100.00        0    NaN
Cancelled            int64        0     0.00        2      0
CancellationCode   float64  5092157   100.00        0    NaN
Diverted             int64        0     0.00        2      0
CarrierDelay       float64  5092157   100.00        0    NaN
WeatherDelay       float64  5092157   100.00        0    NaN
NASDelay           float64  5092157   100.00        0    NaN
SecurityDelay      float64  5092157   100.00        0    NaN
LateAircraftDelay  float64  5092157   100.00        0    NaN

In [7]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

In [8]:
isnull(df)

                      null  nulls_%
Year                     0      0.0
Month                    0      0.0
DayofMonth               0      0.0
DayOfWeek                0      0.0
DepTime                  0      0.0
CRSDepTime               0      0.0
ArrTime                  0      0.0
CRSArrTime               0      0.0
UniqueCarrier            0      0.0
FlightNum                0      0.0
TailNum            5092157    100.0
ActualElapsedTime        0      0.0
CRSElapsedTime           0      0.0
AirTime            5092157    100.0
ArrDelay                 0      0.0
DepDelay                 0      0.0
Origin                   0      0.0
Dest                     0      0.0
Distance                 0      0.0
TaxiIn             5092157    100.0
TaxiOut            5092157    100.0
Cancelled                0      0.0
CancellationCode   5092157    100.0
Diverted                 0      0.0
CarrierDelay       5092157    100.0
WeatherDelay       5092157    100.0
NASDelay           5092157    100.0
SecurityDelay      5092157    100.0
LateAircraftDelay  5092157    100.0

In [9]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

In [10]:
drop_columns(df)

                    dtypes  nulls  nulls_%  nunique sample
Year                 int64      0      0.0        1   1992
Month                int64      0      0.0       12      1
DayofMonth           int64      0      0.0       31      2
DayOfWeek            int64      0      0.0        7      4
DepTime            float64      0      0.0     1434  748.0
CRSDepTime           int64      0      0.0     1260    750
ArrTime            float64      0      0.0     1441  851.0
CRSArrTime           int64      0      0.0     1363    846
UniqueCarrier          str      0      0.0       10     US
FlightNum            int64      0      0.0     2626     53
ActualElapsedTime  float64      0      0.0      618   63.0
CRSElapsedTime       int64      0      0.0      462     56
ArrDelay           float64      0      0.0      697    5.0
DepDelay           float64      0      0.0      701   -2.0
Origin                 str      0      0.0      233    CMH
Dest                   str      0      0.0      233    IND
Distance           float64      0      0.0     1085  182.0
Cancelled            int64      0      0.0        2      0
Diverted             int64      0      0.0        2      0

In [11]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

In [12]:
duplicated(df)

np.int64(0)

In [13]:
def save_to_csv(df):
    df.to_csv('df_1992.csv', index=False, compression='gzip')

In [14]:
save_to_csv(df)