In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1991.csv.bz2', engine='python')

In [3]:
df.head()

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1991,1,1,2,1709.0,1705,1944.0,1944,US,112,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1991,1,2,3,1704.0,1705,1946.0,1944,US,112,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1991,1,3,4,1705.0,1705,1934.0,1944,US,112,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1991,1,4,5,1709.0,1705,1951.0,1944,US,112,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1991,1,5,6,1703.0,1705,1936.0,1944,US,112,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [14]:
df.shape

(5076925, 19)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

In [5]:
adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1991
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31       1
DayOfWeek            int64        0     0.00        7       2
DepTime            float64    43505     0.86     1438  1709.0
CRSDepTime           int64        0     0.00     1220    1705
ArrTime            float64    56090     1.10     1440  1944.0
CRSArrTime           int64        0     0.00     1389    1944
UniqueCarrier          str        0     0.00       12      US
FlightNum            int64        0     0.00     2761     112
TailNum            float64  5076925   100.00        0     NaN
ActualElapsedTime  float64    56090     1.10      617   155.0
CRSElapsedTime       int64        0     0.00      478     159
AirTime            float64  5076925   100.00        0     NaN
ArrDelay           float64    56090     1.10      706     0.0
DepDelay           float64    43505     0.86      701     4.0
Origin                 str        0     0.00      233     TPA
Dest                   str        0     0.00      233     SYR
Distance           float64    26261     0.52     1096  1104.0
TaxiIn             float64  5076925   100.00        0     NaN
TaxiOut            float64  5076925   100.00        0     NaN
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5076925   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5076925   100.00        0     NaN
WeatherDelay       float64  5076925   100.00        0     NaN
NASDelay           float64  5076925   100.00        0     NaN
SecurityDelay      float64  5076925   100.00        0     NaN
LateAircraftDelay  float64  5076925   100.00        0     NaN

In [6]:
def isnulls(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

In [7]:
isnulls(df)

                      null  nulls_%
Year                     0      0.0
Month                    0      0.0
DayofMonth               0      0.0
DayOfWeek                0      0.0
DepTime                  0      0.0
CRSDepTime               0      0.0
ArrTime                  0      0.0
CRSArrTime               0      0.0
UniqueCarrier            0      0.0
FlightNum                0      0.0
TailNum            5076925    100.0
ActualElapsedTime        0      0.0
CRSElapsedTime           0      0.0
AirTime            5076925    100.0
ArrDelay                 0      0.0
DepDelay                 0      0.0
Origin                   0      0.0
Dest                     0      0.0
Distance                 0      0.0
TaxiIn             5076925    100.0
TaxiOut            5076925    100.0
Cancelled                0      0.0
CancellationCode   5076925    100.0
Diverted                 0      0.0
CarrierDelay       5076925    100.0
WeatherDelay       5076925    100.0
NASDelay           5076925    100.0
SecurityDelay      5076925    100.0
LateAircraftDelay  5076925    100.0

In [8]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

In [9]:
drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    1991
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31       1
DayOfWeek            int64      0      0.0        7       2
DepTime            float64      0      0.0     1439  1709.0
CRSDepTime           int64      0      0.0     1220    1705
ArrTime            float64      0      0.0     1441  1944.0
CRSArrTime           int64      0      0.0     1389    1944
UniqueCarrier          str      0      0.0       12      US
FlightNum            int64      0      0.0     2761     112
ActualElapsedTime  float64      0      0.0      618   155.0
CRSElapsedTime       int64      0      0.0      478     159
ArrDelay           float64      0      0.0      707     0.0
DepDelay           float64      0      0.0      702     4.0
Origin                 str      0      0.0      233     TPA
Dest                   str      0      0.0      233     SYR
Distance           float64      0      0.0     1097  1104.0
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [10]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

In [11]:
duplicated(df)

np.int64(0)

In [12]:
def save_to_csv(df):
    df.to_csv('df_1991.csv', index=False)

In [13]:
save_to_csv(df)