In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1996.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1996,1,29,1,2039.0,1930,2245.0,2139,DL,345,...,6,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1996,1,30,2,1931.0,1930,2142.0,2139,DL,345,...,5,22,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1996,1,31,3,1956.0,1930,2231.0,2139,DL,345,...,7,27,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1996,1,1,1,1730.0,1550,1909.0,1745,DL,411,...,4,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1996,1,2,2,1714.0,1550,1841.0,1745,DL,411,...,4,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5351978,1996,12,6,5,1512.0,0,1624.0,0,AA,1885,...,12,14,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5351979,1996,12,7,6,1514.0,0,1633.0,0,AA,1885,...,11,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5351980,1996,12,8,7,1510.0,0,1650.0,0,AA,1885,...,10,21,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5351981,1996,12,9,1,1513.0,0,1616.0,0,AA,1885,...,9,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5351982,1996,12,10,2,1526.0,0,1643.0,0,AA,1885,...,7,22,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5351983 entries, 0 to 5351982
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(13), int64(12), str(4)
memory usage: 1.2 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5351983, 29),
 155207507)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1996
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      29
DayOfWeek            int64        0     0.00        7       1
DepTime            float64   128536     2.40     1435  2039.0
CRSDepTime           int64        0     0.00     1153    1930
ArrTime            float64   142657     2.67     1440  2245.0
CRSArrTime           int64        0     0.00     1345    2139
UniqueCarrier          str        0     0.00       10      DL
FlightNum            int64        0     0.00     2812     345
TailNum                str        0     0.00     3504  N673DL
ActualElapsedTime  float64   142657     2.67      608   246.0
CRSElapsedTime     float64     4646     0.09      457   249.0
AirTime            float64   142657     2.67      576   230.0
ArrDelay           float64   142657     2.67      861    66.0
DepDelay           float64   128536     2.40      881    69.0
Origin                 str        0     0.00      211     ATL
Dest                   str        0     0.00      212     PHX
Distance             int64        0     0.00     1038    1587
TaxiIn               int64        0     0.00      197       6
TaxiOut              int64        0     0.00      302      10
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5351983   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5351983   100.00        0     NaN
WeatherDelay       float64  5351983   100.00        0     NaN
NASDelay           float64  5351983   100.00        0     NaN
SecurityDelay      float64  5351983   100.00        0     NaN
LateAircraftDelay  float64  5351983   100.00        0     NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime        4646     0.09
AirTime             142657     2.67
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5351983   100.00
Diverted                 0     0.00
CarrierDelay       5351983   100.00
WeatherDelay       5351983   100.00
NASDelay           5351983   100.00
SecurityDelay      5351983   100.00
LateAircraftDelay  5351983   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    1996
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31      29
DayOfWeek            int64      0     0.00        7       1
DepTime            float64      0     0.00     1436  2039.0
CRSDepTime           int64      0     0.00     1153    1930
ArrTime            float64      0     0.00     1441  2245.0
CRSArrTime           int64      0     0.00     1345    2139
UniqueCarrier          str      0     0.00       10      DL
FlightNum            int64      0     0.00     2812     345
ActualElapsedTime  float64      0     0.00      609   246.0
CRSElapsedTime     float64   4646     0.09      457   249.0
ArrDelay           float64      0     0.00      862    66.0
DepDelay           float64      0     0.00      882    69.0
Origin                 str      0     0.00      211     ATL
Dest                   str      0     0.00      212     PHX
Distance             int64      0     0.00     1038    1587
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_1996.csv', index=False, compression='gzip')

save_to_csv(df)