In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2005.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2005,1,28,5,1603.0,1605,1741.0,1759,UA,541,...,4,23,0,NaN,0,0,0,0,0,0
1,2005,1,29,6,1559.0,1605,1736.0,1759,UA,541,...,6,15,0,NaN,0,0,0,0,0,0
2,2005,1,30,7,1603.0,1610,1741.0,1805,UA,541,...,9,18,0,NaN,0,0,0,0,0,0
3,2005,1,31,1,1556.0,1605,1726.0,1759,UA,541,...,11,10,0,NaN,0,0,0,0,0,0
4,2005,1,2,7,1934.0,1900,2235.0,2232,UA,542,...,5,10,0,NaN,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7140591,2005,12,22,4,1652.0,1655,1815.0,1837,DL,901,...,7,15,0,NaN,0,0,0,0,0,0
7140592,2005,12,22,4,1825.0,1825,1858.0,1848,DL,902,...,7,32,0,NaN,0,0,0,0,0,0
7140593,2005,12,22,4,1507.0,1511,1641.0,1649,DL,903,...,4,29,0,NaN,0,0,0,0,0,0
7140594,2005,12,22,4,924.0,925,1056.0,1111,DL,904,...,4,19,0,NaN,0,0,0,0,0,0
7140595,2005,12,22,4,1345.0,1344,1621.0,1614,DL,905,...,6,27,0,NaN,0,0,0,0,0,0

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 7140596 entries, 0 to 7140595
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       int64
 25  WeatherDelay       int64
 26  NASDelay           int64
 27  SecurityDelay      int64
 28  LateAircraftDelay  int64
dtypes: float64(6), int64(18), str(5)
memory usage: 1.6 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (7140596, 29),
 207077284)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2005
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      28
DayOfWeek            int64        0     0.00        7       5
DepTime            float64   133730     1.87     1584  1603.0
CRSDepTime           int64        0     0.00     1185    1605
ArrTime            float64   147758     2.07     1664  1741.0
CRSArrTime           int64        0     0.00     1356    1759
UniqueCarrier          str        0     0.00       20      UA
FlightNum            int64        0     0.00     6938     541
TailNum                str        0     0.00     5093  N935UA
ActualElapsedTime  float64   147758     2.07      783   158.0
CRSElapsedTime       int64        0     0.00      541     174
AirTime            float64   147758     2.07      892   131.0
ArrDelay           float64   147758     2.07     1136   -18.0
DepDelay           float64   133730     1.87     1202    -2.0
Origin                 str        0     0.00      286     BOS
Dest                   str        0     0.00      289     ORD
Distance             int64        0     0.00     1346     867
TaxiIn               int64        0     0.00      237       4
TaxiOut              int64        0     0.00      311      23
Cancelled            int64        0     0.00        2       0
CancellationCode       str  7006865    98.13        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay         int64        0     0.00      935       0
WeatherDelay         int64        0     0.00      540       0
NASDelay             int64        0     0.00      548       0
SecurityDelay        int64        0     0.00      182       0
LateAircraftDelay    int64        0     0.00      539       0

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime           0     0.00
AirTime             147758     2.07
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   7006865    98.13
Diverted                 0     0.00
CarrierDelay             0     0.00
WeatherDelay             0     0.00
NASDelay                 0     0.00
SecurityDelay            0     0.00
LateAircraftDelay        0     0.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0      0.0        1    2005
Month                int64      0      0.0       12       1
DayofMonth           int64      0      0.0       31      28
DayOfWeek            int64      0      0.0        7       5
DepTime            float64      0      0.0     1585  1603.0
CRSDepTime           int64      0      0.0     1185    1605
ArrTime            float64      0      0.0     1665  1741.0
CRSArrTime           int64      0      0.0     1356    1759
UniqueCarrier          str      0      0.0       20      UA
FlightNum            int64      0      0.0     6938     541
ActualElapsedTime  float64      0      0.0      784   158.0
CRSElapsedTime       int64      0      0.0      541     174
ArrDelay           float64      0      0.0     1137   -18.0
DepDelay           float64      0      0.0     1203    -2.0
Origin                 str      0      0.0      286     BOS
Dest                   str      0      0.0      289     ORD
Distance             int64      0      0.0     1346     867
Cancelled            int64      0      0.0        2       0
Diverted             int64      0      0.0        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(11)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2005.csv', index=False, compression='gzip')

save_to_csv(df)