In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1999.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1999,1,27,3,1906.0,1908,2024.0,2005,US,1244,...,3,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1999,1,28,4,2016.0,1908,2126.0,2005,US,1244,...,19,10,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1999,1,29,5,1907.0,1908,2000.0,2005,US,1244,...,2,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1999,1,31,7,1932.0,1908,2031.0,2005,US,1244,...,6,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1999,1,1,5,1601.0,1535,1707.0,1645,US,297,...,11,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5527879,1999,12,16,4,1910.0,1910,2112.0,2117,AA,1359,...,14,12,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5527880,1999,12,17,5,1909.0,1910,2111.0,2117,AA,1359,...,10,15,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5527881,1999,12,18,6,1907.0,1910,2103.0,2117,AA,1359,...,12,9,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5527882,1999,12,19,7,1907.0,1910,2114.0,2117,AA,1359,...,11,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5527883,1999,12,20,1,1905.0,1910,2127.0,2117,AA,1359,...,15,8,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5527884 entries, 0 to 5527883
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(13), int64(12), str(4)
memory usage: 1.3 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5527884, 29),
 160308636)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1999
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31      27
DayOfWeek            int64        0     0.00        7       3
DepTime            float64   154311     2.79     1428  1906.0
CRSDepTime           int64        0     0.00     1183    1908
ArrTime            float64   167866     3.04     1440  2024.0
CRSArrTime           int64        0     0.00     1369    2005
UniqueCarrier          str        0     0.00       10      US
FlightNum            int64        0     0.00     3032    1244
TailNum                str        0     0.00     3933  N942VJ
ActualElapsedTime  float64   167866     3.04      672    78.0
CRSElapsedTime     float64     8992     0.16      489    57.0
AirTime            float64   167866     3.04      625    66.0
ArrDelay           float64   167866     3.04      990    19.0
DepDelay           float64   154311     2.79      988    -2.0
Origin                 str        0     0.00      205     RIC
Dest                   str        0     0.00      205     PHL
Distance             int64        0     0.00     1070     198
TaxiIn               int64        0     0.00      213       3
TaxiOut              int64        0     0.00      330       9
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5527884   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5527884   100.00        0     NaN
WeatherDelay       float64  5527884   100.00        0     NaN
NASDelay           float64  5527884   100.00        0     NaN
SecurityDelay      float64  5527884   100.00        0     NaN
LateAircraftDelay  float64  5527884   100.00        0     NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime        8992     0.16
AirTime             167866     3.04
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5527884   100.00
Diverted                 0     0.00
CarrierDelay       5527884   100.00
WeatherDelay       5527884   100.00
NASDelay           5527884   100.00
SecurityDelay      5527884   100.00
LateAircraftDelay  5527884   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    1999
Month                int64      0     0.00       12       1
DayofMonth           int64      0     0.00       31      27
DayOfWeek            int64      0     0.00        7       3
DepTime            float64      0     0.00     1429  1906.0
CRSDepTime           int64      0     0.00     1183    1908
ArrTime            float64      0     0.00     1441  2024.0
CRSArrTime           int64      0     0.00     1369    2005
UniqueCarrier          str      0     0.00       10      US
FlightNum            int64      0     0.00     3032    1244
ActualElapsedTime  float64      0     0.00      673    78.0
CRSElapsedTime     float64   8992     0.16      489    57.0
ArrDelay           float64      0     0.00      991    19.0
DepDelay           float64      0     0.00      989    -2.0
Origin                 str      0     0.00      205     RIC
Dest                   str      0     0.00      205     PHL
Distance             int64      0     0.00     1070     198
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_1999.csv', index=False, compression='gzip')

save_to_csv(df)