In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1995.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1995,1,6,5,657.0,645,952.0,937,UA,482,...,7,25,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1995,1,7,6,648.0,645,938.0,937,UA,482,...,5,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1995,1,8,7,649.0,645,932.0,937,UA,482,...,3,17,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1995,1,9,1,645.0,645,928.0,937,UA,482,...,3,16,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1995,1,10,2,645.0,645,931.0,937,UA,482,...,6,18,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327430,1995,12,12,2,2217.0,2215,2332.0,2332,TW,427,...,5,12,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5327431,1995,12,13,3,2216.0,2215,2355.0,2332,TW,427,...,6,24,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5327432,1995,12,14,4,2215.0,2215,2341.0,2332,TW,427,...,5,16,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5327433,1995,12,15,5,2236.0,2215,2348.0,2332,TW,427,...,5,13,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5327434,1995,12,17,7,2215.0,2215,2328.0,2332,TW,427,...,6,16,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5327435 entries, 0 to 5327434
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           float64
 19  TaxiIn             int64
 20  TaxiOut            int64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(14), int64(11), str(4)
memory usage: 1.2 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5327435, 29),
 154495615)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    1995
Month                int64        0     0.00       12       1
DayofMonth           int64        0     0.00       31       6
DayOfWeek            int64        0     0.00        7       5
DepTime            float64    91905     1.73     1429   657.0
CRSDepTime           int64        0     0.00     1141     645
ArrTime            float64   102397     1.92     1440   952.0
CRSArrTime           int64        0     0.00     1356     937
UniqueCarrier          str        0     0.00       10      UA
FlightNum            int64        0     0.00     3009     482
TailNum                str        0     0.00     3508  N7298U
ActualElapsedTime  float64   102397     1.92      620   115.0
CRSElapsedTime     float64     3249     0.06      453   112.0
AirTime            float64    50349     0.95      583    83.0
ArrDelay           float64   102397     1.92      760    15.0
DepDelay           float64    91905     1.73      771    12.0
Origin                 str        0     0.00      218     ORD
Dest                   str        0     0.00      218     PHL
Distance           float64     5987     0.11     1055   678.0
TaxiIn               int64        0     0.00      186       7
TaxiOut              int64        0     0.00      323      25
Cancelled            int64        0     0.00        2       0
CancellationCode   float64  5327435   100.00        0     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  5327435   100.00        0     NaN
WeatherDelay       float64  5327435   100.00        0     NaN
NASDelay           float64  5327435   100.00        0     NaN
SecurityDelay      float64  5327435   100.00        0     NaN
LateAircraftDelay  float64  5327435   100.00        0     NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum                  0     0.00
ActualElapsedTime        0     0.00
CRSElapsedTime        3249     0.06
AirTime              50349     0.95
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn                   0     0.00
TaxiOut                  0     0.00
Cancelled                0     0.00
CancellationCode   5327435   100.00
Diverted                 0     0.00
CarrierDelay       5327435   100.00
WeatherDelay       5327435   100.00
NASDelay           5327435   100.00
SecurityDelay      5327435   100.00
LateAircraftDelay  5327435   100.00

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique sample
Year                 int64      0     0.00        1   1995
Month                int64      0     0.00       12      1
DayofMonth           int64      0     0.00       31      6
DayOfWeek            int64      0     0.00        7      5
DepTime            float64      0     0.00     1430  657.0
CRSDepTime           int64      0     0.00     1141    645
ArrTime            float64      0     0.00     1441  952.0
CRSArrTime           int64      0     0.00     1356    937
UniqueCarrier          str      0     0.00       10     UA
FlightNum            int64      0     0.00     3009    482
ActualElapsedTime  float64      0     0.00      621  115.0
CRSElapsedTime     float64   3249     0.06      453  112.0
ArrDelay           float64      0     0.00      761   15.0
DepDelay           float64      0     0.00      772   12.0
Origin                 str      0     0.00      218    ORD
Dest                   str      0     0.00      218    PHL
Distance           float64      0     0.00     1056  678.0
Cancelled            int64      0     0.00        2      0
Diverted             int64      0     0.00        2      0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_1995.csv', index=False, compression='gzip')

save_to_csv(df)

In [11]:
pd.read_csv('df_1995.csv', compression='gzip', engine='pyarrow')

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,ActualElapsedTime,CRSElapsedTime,ArrDelay,DepDelay,Origin,Dest,Distance,Cancelled,Diverted
0,1995,1,6,5,657.0,645,952.0,937,UA,482,115.0,112.0,15.0,12.0,ORD,PHL,678.0,0,0
1,1995,1,7,6,648.0,645,938.0,937,UA,482,110.0,112.0,1.0,3.0,ORD,PHL,678.0,0,0
2,1995,1,8,7,649.0,645,932.0,937,UA,482,103.0,112.0,-5.0,4.0,ORD,PHL,678.0,0,0
3,1995,1,9,1,645.0,645,928.0,937,UA,482,103.0,112.0,-9.0,0.0,ORD,PHL,678.0,0,0
4,1995,1,10,2,645.0,645,931.0,937,UA,482,106.0,112.0,-6.0,0.0,ORD,PHL,678.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5327430,1995,12,12,2,2217.0,2215,2332.0,2332,TW,427,135.0,137.0,0.0,2.0,STL,DEN,770.0,0,0
5327431,1995,12,13,3,2216.0,2215,2355.0,2332,TW,427,159.0,137.0,23.0,1.0,STL,DEN,770.0,0,0
5327432,1995,12,14,4,2215.0,2215,2341.0,2332,TW,427,146.0,137.0,9.0,0.0,STL,DEN,770.0,0,0
5327433,1995,12,15,5,2236.0,2215,2348.0,2332,TW,427,132.0,137.0,16.0,21.0,STL,DEN,770.0,0,0
5327434,1995,12,17,7,2215.0,2215,2328.0,2332,TW,427,133.0,137.0,-4.0,0.0,STL,DEN,770.0,0,0