In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/1994.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,1994,1,7,5,858.0,900,954.0,1003,US,227,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
1,1994,1,8,6,859.0,900,952.0,1003,US,227,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,1994,1,10,1,935.0,900,1023.0,1003,US,227,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,1994,1,11,2,903.0,900,1131.0,1003,US,227,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,1994,1,12,3,933.0,900,1024.0,1003,US,227,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5180043,1994,12,25,7,1716.0,1715,1923.0,1945,DL,149,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5180044,1994,12,26,1,1716.0,1715,1910.0,1945,DL,149,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5180045,1994,12,27,2,1721.0,1715,1930.0,1945,DL,149,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5180046,1994,12,28,3,1715.0,1715,1934.0,1945,DL,149,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN
5180047,1994,12,29,4,1715.0,1715,1941.0,1945,DL,149,...,NaN,NaN,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 5180048 entries, 0 to 5180047
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            float64
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     int64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           float64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   float64
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(16), int64(10), str(3)
memory usage: 1.2 GB

(Empty DataFrame
 Columns: []
 Index: [],
 (5180048, 29),
 150221392)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique sample
Year                 int64        0     0.00        1   1994
Month                int64        0     0.00       12      1
DayofMonth           int64        0     0.00       31      7
DayOfWeek            int64        0     0.00        7      5
DepTime            float64    66740     1.29     1420  858.0
CRSDepTime           int64        0     0.00     1162    900
ArrTime            float64    78846     1.52     1440  954.0
CRSArrTime           int64        0     0.00     1351   1003
UniqueCarrier          str        0     0.00       10     US
FlightNum            int64        0     0.00     3012    227
TailNum            float64  5180048   100.00        0    NaN
ActualElapsedTime  float64    78846     1.52      605   56.0
CRSElapsedTime       int64        0     0.00      447     63
AirTime            float64  5180048   100.00        0    NaN
ArrDelay           float64    78846     1.52      632   -9.0
DepDelay           float64    66740     1.29      652   -2.0
Origin                 str        0     0.00      224    CLT
Dest                   str        0     0.00      225    ORF
Distance           float64    22949     0.44     1040  290.0
TaxiIn             float64  5180048   100.00        0    NaN
TaxiOut            float64  5180048   100.00        0    NaN
Cancelled            int64        0     0.00        2      0
CancellationCode   float64  5180048   100.00        0    NaN
Diverted             int64        0     0.00        2      0
CarrierDelay       float64  5180048   100.00        0    NaN
WeatherDelay       float64  5180048   100.00        0    NaN
NASDelay           float64  5180048   100.00        0    NaN
SecurityDelay      float64  5180048   100.00        0    NaN
LateAircraftDelay  float64  5180048   100.00        0    NaN

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0      0.0
Month                    0      0.0
DayofMonth               0      0.0
DayOfWeek                0      0.0
DepTime                  0      0.0
CRSDepTime               0      0.0
ArrTime                  0      0.0
CRSArrTime               0      0.0
UniqueCarrier            0      0.0
FlightNum                0      0.0
TailNum            5180048    100.0
ActualElapsedTime        0      0.0
CRSElapsedTime           0      0.0
AirTime            5180048    100.0
ArrDelay                 0      0.0
DepDelay                 0      0.0
Origin                   0      0.0
Dest                     0      0.0
Distance                 0      0.0
TaxiIn             5180048    100.0
TaxiOut            5180048    100.0
Cancelled                0      0.0
CancellationCode   5180048    100.0
Diverted                 0      0.0
CarrierDelay       5180048    100.0
WeatherDelay       5180048    100.0
NASDelay           5180048    100.0
SecurityDelay      5180048    100.0
LateAircraftDelay  5180048    100.0

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique sample
Year                 int64      0      0.0        1   1994
Month                int64      0      0.0       12      1
DayofMonth           int64      0      0.0       31      7
DayOfWeek            int64      0      0.0        7      5
DepTime            float64      0      0.0     1421  858.0
CRSDepTime           int64      0      0.0     1162    900
ArrTime            float64      0      0.0     1441  954.0
CRSArrTime           int64      0      0.0     1351   1003
UniqueCarrier          str      0      0.0       10     US
FlightNum            int64      0      0.0     3012    227
ActualElapsedTime  float64      0      0.0      606   56.0
CRSElapsedTime       int64      0      0.0      447     63
ArrDelay           float64      0      0.0      633   -9.0
DepDelay           float64      0      0.0      653   -2.0
Origin                 str      0      0.0      224    CLT
Dest                   str      0      0.0      225    ORF
Distance           float64      0      0.0     1041  290.0
Cancelled            int64      0      0.0        2      0
Diverted             int64      0      0.0        2      0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(0)

In [8]:
def save_to_csv(df):
    df.to_csv('df_1994.csv', index=False, compression='gzip')

save_to_csv(df)