In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataverse_files/2008.csv.bz2', engine='pyarrow')
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,1343.0,1325,1451.0,1435,WN,588,...,4.0,9.0,0,NaN,0,16.0,0.0,0.0,0.0,0.0
1,2008,1,3,4,1125.0,1120,1247.0,1245,WN,1343,...,3.0,8.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,2009.0,2015,2136.0,2140,WN,3841,...,2.0,14.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,903.0,855,1203.0,1205,WN,3,...,5.0,7.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
4,2008,1,3,4,1423.0,1400,1726.0,1710,WN,25,...,6.0,10.0,0,NaN,0,16.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2389212,2008,4,17,4,1025.0,1025,1234.0,1237,DL,1207,...,5.0,16.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2389213,2008,4,17,4,1319.0,1320,1527.0,1524,DL,1208,...,9.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2389214,2008,4,17,4,1335.0,1335,1556.0,1553,DL,1209,...,7.0,31.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2389215,2008,4,17,4,1933.0,1935,2140.0,2141,DL,1210,...,9.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN
2389216,2008,4,17,4,621.0,615,752.0,754,DL,1211,...,15.0,12.0,0,NaN,0,NaN,NaN,NaN,NaN,NaN

In [3]:
def df_info(df):
    summary = pd.DataFrame(df.info())
    shape = df.shape
    size = df.size
    return summary, shape, size

df_info(df)

<class 'pandas.DataFrame'>
RangeIndex: 2389217 entries, 0 to 2389216
Data columns (total 29 columns):
 #   Column             Dtype
---  ------             -----
 0   Year               int64
 1   Month              int64
 2   DayofMonth         int64
 3   DayOfWeek          int64
 4   DepTime            float64
 5   CRSDepTime         int64
 6   ArrTime            float64
 7   CRSArrTime         int64
 8   UniqueCarrier      str
 9   FlightNum          int64
 10  TailNum            str
 11  ActualElapsedTime  float64
 12  CRSElapsedTime     float64
 13  AirTime            float64
 14  ArrDelay           float64
 15  DepDelay           float64
 16  Origin             str
 17  Dest               str
 18  Distance           int64
 19  TaxiIn             float64
 20  TaxiOut            float64
 21  Cancelled          int64
 22  CancellationCode   str
 23  Diverted           int64
 24  CarrierDelay       float64
 25  WeatherDelay       float64
 26  NASDelay           float64
 27  SecurityDelay      float64
 28  LateAircraftDelay  float64
dtypes: float64(14), int64(10), str(5)
memory usage: 560.8 MB

(Empty DataFrame
 Columns: []
 Index: [],
 (2389217, 29),
 69287293)

In [4]:
def adult(df):
    summary = pd.DataFrame({
        'dtypes': df.dtypes,
        'nulls': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2),
        'nunique': df.nunique(),
        'sample': df.iloc[0]
    })
    return summary

adult(df)

                    dtypes    nulls  nulls_%  nunique  sample
Year                 int64        0     0.00        1    2008
Month                int64        0     0.00        4       1
DayofMonth           int64        0     0.00       31       3
DayOfWeek            int64        0     0.00        7       4
DepTime            float64    64442     2.70     1434  1343.0
CRSDepTime           int64        0     0.00     1158    1325
ArrTime            float64    70096     2.93     1440  1451.0
CRSArrTime           int64        0     0.00     1331    1435
UniqueCarrier          str        0     0.00       20      WN
FlightNum            int64        0     0.00     7269     588
TailNum                str    42452     1.78     5031  N240WN
ActualElapsedTime  float64    70096     2.93      668    68.0
CRSElapsedTime     float64      407     0.02      476    70.0
AirTime            float64    70096     2.93      648    55.0
ArrDelay           float64    70096     2.93      935    16.0
DepDelay           float64    64442     2.70      921    18.0
Origin                 str        0     0.00      291     HOU
Dest                   str        0     0.00      293     LIT
Distance             int64        0     0.00     1377     393
TaxiIn             float64    70096     2.93      165     4.0
TaxiOut            float64    64442     2.70      277     9.0
Cancelled            int64        0     0.00        2       0
CancellationCode       str  2324775    97.30        4     NaN
Diverted             int64        0     0.00        2       0
CarrierDelay       float64  1804634    75.53      781    16.0
WeatherDelay       float64  1804634    75.53      481     0.0
NASDelay           float64  1804634    75.53      483     0.0
SecurityDelay      float64  1804634    75.53      109     0.0
LateAircraftDelay  float64  1804634    75.53      474     0.0

In [5]:
def isnull(df):
    df['DepTime'] = df['DepTime'].fillna(df['DepTime'].mean()) 
    df['ArrTime'] = df['ArrTime'].fillna(df['ArrTime'].mean()) 
    df['ActualElapsedTime'] = df['ActualElapsedTime'].fillna(df['ActualElapsedTime'].mean()) 
    df['ArrDelay'] = df['ArrDelay'].fillna(df['ArrDelay'].mean()) 
    df['DepDelay'] = df['DepDelay'].fillna(df['DepDelay'].mean()) 
    df['Distance'] = df['Distance'].fillna(0) 

    summary = pd.DataFrame({
        'null': df.isnull().sum(),
        'nulls_%': (df.isnull().mean() * 100).round(2)
    })
    return summary

isnull(df)

                      null  nulls_%
Year                     0     0.00
Month                    0     0.00
DayofMonth               0     0.00
DayOfWeek                0     0.00
DepTime                  0     0.00
CRSDepTime               0     0.00
ArrTime                  0     0.00
CRSArrTime               0     0.00
UniqueCarrier            0     0.00
FlightNum                0     0.00
TailNum              42452     1.78
ActualElapsedTime        0     0.00
CRSElapsedTime         407     0.02
AirTime              70096     2.93
ArrDelay                 0     0.00
DepDelay                 0     0.00
Origin                   0     0.00
Dest                     0     0.00
Distance                 0     0.00
TaxiIn               70096     2.93
TaxiOut              64442     2.70
Cancelled                0     0.00
CancellationCode   2324775    97.30
Diverted                 0     0.00
CarrierDelay       1804634    75.53
WeatherDelay       1804634    75.53
NASDelay           1804634    75.53
SecurityDelay      1804634    75.53
LateAircraftDelay  1804634    75.53

In [6]:
def drop_columns(df):
    columns = ['TailNum', 'SecurityDelay', "TaxiIn", 'TaxiOut', 'LateAircraftDelay', 'CancellationCode', 'CarrierDelay', 'NASDelay', 'WeatherDelay', 'AirTime']
    df.drop(columns=columns, inplace=True)
    return adult(df)

drop_columns(df)

                    dtypes  nulls  nulls_%  nunique  sample
Year                 int64      0     0.00        1    2008
Month                int64      0     0.00        4       1
DayofMonth           int64      0     0.00       31       3
DayOfWeek            int64      0     0.00        7       4
DepTime            float64      0     0.00     1435  1343.0
CRSDepTime           int64      0     0.00     1158    1325
ArrTime            float64      0     0.00     1441  1451.0
CRSArrTime           int64      0     0.00     1331    1435
UniqueCarrier          str      0     0.00       20      WN
FlightNum            int64      0     0.00     7269     588
ActualElapsedTime  float64      0     0.00      669    68.0
CRSElapsedTime     float64    407     0.02      476    70.0
ArrDelay           float64      0     0.00      936    16.0
DepDelay           float64      0     0.00      922    18.0
Origin                 str      0     0.00      291     HOU
Dest                   str      0     0.00      293     LIT
Distance             int64      0     0.00     1377     393
Cancelled            int64      0     0.00        2       0
Diverted             int64      0     0.00        2       0

In [7]:
def duplicated(df):
    drop = df.duplicated().sum()
    df.drop_duplicates(inplace=True)
    return drop

duplicated(df)

np.int64(4)

In [8]:
def save_to_csv(df):
    df.to_csv('df_2008.csv', index=False, compression='gzip')

save_to_csv(df)